server:
  port: 8001    

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.atguigu.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
    
spring:
   application:
    name: springCloud-provider                              # 服务对外提供的应用名称
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/springcloud          # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

#配置eureka
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:     
      #defaultZone: http://localhost:7001/eureka   #eureka的注册地址（即eureka项目中application.yml中配置得defaultZone）
      defaultZone: http://peer1:7001/eureka/,http://peer2:7002/eureka/,http://peer3:7003/eureka/      
  instance:
    instance-id: springcloud-8001   #该服务提供者在eureka中的名字
    prefer-ip-address: true     #访问路径可以显示IP地址  
    
  
info: 
  app.name: I am springcloud-provider-8001           #跳转到info页面后的服务提供者的信息
  company.name: cn.gxm
  build.artifactId: springCloud-provider-8001
  build.version: 0.0.1-SNAPSHOT   
    
